using static Microsoft.VisualBasic.Constants;
using static modConvert;


static class frmTest
{
    // Option Explicit


    public static string TestCase()
    {
        string TestCase = "";
        string A = "";
        string N = "";
        string M = "";

        A = "";
        M = "";
        N = vbCrLf;

        A = A + M + "Public Function ReadEntireFile(ByVal FileName As String) As String";
        A = A + N + "'::::ReadEntireFile";
        A = A + N + "':::SUMMARY";
        A = A + N + "':Read an entire file.";
        A = A + N + "':::DESCRIPTION";
        A = A + N + "':Reads  the full contents of a file and returns the value as a string (without modification).";
        A = A + N + "':::PARAMETERS";
        A = A + N + "':- FileName - The name of the file to read.";
        A = A + N + "':::RETURN";
        A = A + N + "':  String - The string contents of the file.";
        A = A + N + "':::SEE ALSO";
        A = A + N + "':  ReadFile, WriteFile, ReadEntireFileAndDelete";
        A = A + N + "";
        A = A + N + "On Error Resume Next";
        A = A + N + "  With CreateObject(\"Scripting.FileSystemObject\")";
        A = A + N + "    ReadEntireFile = .OpenTextFile(FileName, 1).ReadAll";
        A = A + N + "  End With";
        A = A + N + "  ";
        A = A + N + "  If FileLen(FileName) / 10 <> Len(ReadEntireFile) / 10 Then";
        A = A + N + "    MsgBox \"ReadEntireFile was short: \" & FileLen(FileName) & \" vs \" & Len(ReadEntireFile)";
        A = A + N + "  End If";
        A = A + N + "'";
        A = A + N + "'  Dim intFile As Long";
        A = A + N + "'  intFile = FreeFile";
        A = A + N + "'On Error Resume Next";
        A = A + N + "'  Open FileName For Input As #intFile";
        A = A + N + "'  ReadEntireFile = Input$(LOF(intFile), #intFile)  '  LOF returns Length of File";
        A = A + N + "'  Close #intFile";
        A = A + N + "End Function";
        TestCase = A;
        return TestCase;
    }

    public static dynamic TestCase2()
    {
        dynamic TestCase2 = null;
        string A = "";
        string N = "";
        string M = "";

        A = "";
        M = "";
        N = vbCrLf;

        A = A + N + "Public Function DescribeColor(ByVal RGB As Long) As String";
        A = A + N + "  Dim R As Long, G As Long, B As Long";
        A = A + N + "  Select Case RGB";
        A = A + N + "    Case vbBlack:     DescribeColor = \"BLACK\"";
        A = A + N + "    Case vbBlue:      DescribeColor = \"BLUE\"";
        A = A + N + "    Case vbCyan:      DescribeColor = \"CYAN\"";
        A = A + N + "    Case vbGreen:     DescribeColor = \"GREEN\"";
        A = A + N + "    Case vbMagenta:   DescribeColor = \"MAGENTA\"";
        A = A + N + "    Case vbRed:       DescribeColor = \"RED\"";
        A = A + N + "    Case vbWhite:     DescribeColor = \"WHITE\"";
        A = A + N + "    Case vbYellow:    DescribeColor = \"YELLOW\"";
        A = A + N + "";
        A = A + N + "    Case Else";
        A = A + N + "      DescribeColor = \"OTHER\"";
        A = A + N + "      R = RGB And 255";
        A = A + N + "      G = (RGB And 65280) / 256";
        A = A + N + "      B = (RGB And 16711680) / 65536";
        A = A + N + "      DescribeColor = DescribeColor & \" (R:\" & R & \",G:\" & G & \",:\" & B & \")\"";
        A = A + N + "  End Select";
        A = A + N + "";
        A = A + N + " ' If SingleLineIf Then DoSomeStuff: AndMore()";
        A = A + N + "";
        A = A + N + "GotoLabel:";
        A = A + N + "  SomeFunction()";
        A = A + N + "End Function";

        TestCase2 = SanitizeCode(A);
        return TestCase2;
    }

    public static string TestCaseFrm()
    {
        string TestCaseFrm = "";
        string S = "";
        string N = "";

        N = vbCrLf;
        S = S + N + "VERSION 5.00";
        S = S + N + "Begin VB.Form frmAbout ";
        S = S + N + "   BackColor       =   &H000000FF&";
        S = S + N + "   BorderStyle     =   0  'None";
        S = S + N + "   ClientHeight    =   4485";
        S = S + N + "   ClientLeft      =   0";
        S = S + N + "   ClientTop       =   0";
        S = S + N + "   ClientWidth     =   6300";
        S = S + N + "   Icon            =   \"frmAbout.frx\":0000";
        S = S + N + "   LinkTopic       =   \"Form1\"";
        S = S + N + "   ScaleHeight     =   4485";
        S = S + N + "   ScaleWidth      =   6300";
        S = S + N + "   ShowInTaskbar   =   0   'False";
        S = S + N + "   StartUpPosition =   2  'CenterScreen";
        S = S + N + "   Begin VB.Timer tmr ";
        S = S + N + "      Interval        =   150";
        S = S + N + "      Left            =   5760";
        S = S + N + "      Top             =   120";
        S = S + N + "   End";
        S = S + N + "   Begin VB.Label lblInfo ";
        S = S + N + "      Appearance      =   0  'Flat";
        S = S + N + "      BackColor       =   &H80000005&";
        S = S + N + "      BackStyle       =   0  'Transparent";
        S = S + N + "      BorderStyle     =   1  'Fixed Single";
        S = S + N + "      Caption         =   \"###\"";
        S = S + N + "      ForeColor       =   &H80000008&";
        S = S + N + "      Height          =   2175";
        S = S + N + "      Left            =   2400";
        S = S + N + "      TabIndex        =   0";
        S = S + N + "      Top             =   2160";
        S = S + N + "      Width           =   3735";
        S = S + N + "   End";
        S = S + N + "   Begin VB.Shape shpFrame ";
        S = S + N + "      BorderWidth     =   3";
        S = S + N + "      Height          =   4440";
        S = S + N + "      Left            =   15";
        S = S + N + "      Top             =   15";
        S = S + N + "      Width           =   6270";
        S = S + N + "   End";
        S = S + N + "   Begin VB.Image imgBacking ";
        S = S + N + "      Height          =   975";
        S = S + N + "      Left            =   1320";
        S = S + N + "      Stretch         =   -1  'True";
        S = S + N + "      Top             =   600";
        S = S + N + "      Width           =   1335";
        S = S + N + "   End";
        S = S + N + "End";
        S = S + N + "Attribute VB_Name = \"frmAbout\"";
        S = S + N + "Attribute VB_GlobalNameSpace = False";
        S = S + N + "Attribute VB_Creatable = False";
        S = S + N + "Attribute VB_PredeclaredId = True";
        S = S + N + "Attribute VB_Exposed = False";
        S = S + N + "";

        TestCaseFrm = S;
        return TestCaseFrm;
    }

    public static string TestCaseFrm2()
    {
        string TestCaseFrm2 = "";
        string S = "";
        string N = "";
        string M = "";

        S = "";
        N = vbCrLf;
        M = "";
        S = "";
        S = S + N + "VERSION 5.00";
        S = S + N + "Object = \"{86CF1D34-0C5F-11D2-A9FC-0000F8754DA1}#2.0#0\"; \"Mscomct2.ocx\"";
        S = S + N + "Begin VB.Form ARPaySetUp ";
        S = S + N + "   BorderStyle     =   1  'Fixed Single";
        S = S + N + "   Caption         =   \"Payment Set Up\"";
        S = S + N + "   ClientHeight    =   8820";
        S = S + N + "   ClientLeft      =   45";
        S = S + N + "   ClientTop       =   330";
        S = S + N + "   ClientWidth     =   4815";
        S = S + N + "   Icon            =   \"ArPaySetUp.frx\":0000";
        S = S + N + "   LinkTopic       =   \"Form2\"";
        S = S + N + "   MaxButton       =   0   'False";
        S = S + N + "   ScaleHeight     =   8820";
        S = S + N + "   ScaleWidth      =   4815";
        S = S + N + "   StartUpPosition =   2  'CenterScreen";
        S = S + N + "   Begin VB.PictureBox picPicture ";
        S = S + N + "      Height          =   375";
        S = S + N + "      Left            =   4080";
        S = S + N + "      ScaleHeight     =   315";
        S = S + N + "      ScaleWidth      =   375";
        S = S + N + "      TabIndex        =   70";
        S = S + N + "      Top             =   360";
        S = S + N + "      Visible         =   0   'False";
        S = S + N + "      Width           =   435";
        S = S + N + "   End";
        S = S + N + "   Begin VB.Frame fraARPaySetup ";
        S = S + N + "      BeginProperty Font ";
        S = S + N + "         Name            =   \"MS Sans Serif\"";
        S = S + N + "         Size            =   9.75";
        S = S + N + "         Charset         =   0";
        S = S + N + "         Weight          =   400";
        S = S + N + "         Underline       =   0   'False";
        S = S + N + "         Italic          =   0   'False";
        S = S + N + "         Strikethrough   =   0   'False";
        S = S + N + "      EndProperty";
        S = S + N + "      Height          =   8595";
        S = S + N + "      Left            =   120";
        S = S + N + "      TabIndex        =   68";
        S = S + N + "      Top             =   120";
        S = S + N + "      Width           =   4575";
        S = S + N + "      Begin VB.TextBox txtUnemploymentInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   35";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   4920";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CheckBox chkUnemployment ";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   2820";
        S = S + N + "         TabIndex        =   36";
        S = S + N + "         Top             =   4920";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   255";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtTotalBalance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         Locked          =   -1  'True";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   52";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   6960";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Frame fraJointLife ";
        S = S + N + "         BorderStyle     =   0  'None";
        S = S + N + "         Height          =   495";
        S = S + N + "         Left            =   3120";
        S = S + N + "         TabIndex        =   79";
        S = S + N + "         Top             =   4200";
        S = S + N + "         Width           =   1335";
        S = S + N + "         Begin VB.OptionButton optJointLife ";
        S = S + N + "            Caption         =   \"Joint Life\"";
        S = S + N + "            Height          =   255";
        S = S + N + "            Index           =   1";
        S = S + N + "            Left            =   120";
        S = S + N + "            TabIndex        =   57";
        S = S + N + "            Top             =   240";
        S = S + N + "            Width           =   975";
        S = S + N + "         End";
        S = S + N + "         Begin VB.OptionButton optJointLife ";
        S = S + N + "            Caption         =   \"Single Life\"";
        S = S + N + "            Height          =   255";
        S = S + N + "            Index           =   0";
        S = S + N + "            Left            =   120";
        S = S + N + "            TabIndex        =   56";
        S = S + N + "            Top             =   0";
        S = S + N + "            Value           =   -1  'True";
        S = S + N + "            Width           =   1095";
        S = S + N + "         End";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Timer tmrLoad ";
        S = S + N + "         Enabled         =   0   'False";
        S = S + N + "         Interval        =   10";
        S = S + N + "         Left            =   3840";
        S = S + N + "         Top             =   960";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CheckBox chkRoundUp ";
        S = S + N + "         Caption         =   \"Round Up\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   1800";
        S = S + N + "         TabIndex        =   55";
        S = S + N + "         Top             =   7800";
        S = S + N + "         Value           =   1  'Checked";
        S = S + N + "         Width           =   1095";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CommandButton cmdCancel ";
        S = S + N + "         Cancel          =   -1  'True";
        S = S + N + "         Caption         =   \"&Cancel\"";
        S = S + N + "         Height          =   315";
        S = S + N + "         Left            =   3120";
        S = S + N + "         TabIndex        =   64";
        S = S + N + "         Top             =   8160";
        S = S + N + "         Width           =   1215";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CommandButton cmdApply ";
        S = S + N + "         Caption         =   \"&Apply\"";
        S = S + N + "         Height          =   375";
        S = S + N + "         Left            =   3720";
        S = S + N + "         TabIndex        =   63";
        S = S + N + "         Top             =   7800";
        S = S + N + "         Width           =   615";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CommandButton cmdPrint ";
        S = S + N + "         Caption         =   \"&Print\"";
        S = S + N + "         Height          =   375";
        S = S + N + "         Left            =   3120";
        S = S + N + "         TabIndex        =   62";
        S = S + N + "         Top             =   7800";
        S = S + N + "         Width           =   615";
        S = S + N + "      End";
        S = S + N + "      Begin VB.ComboBox cboCashOption ";
        S = S + N + "         Height          =   315";
        S = S + N + "         ItemData        =   \"ArPaySetUp.frx\":030A";
        S = S + N + "         Left            =   1800";
        S = S + N + "         List            =   \"ArPaySetUp.frx\":030C";
        S = S + N + "         Style           =   2  'Dropdown List";
        S = S + N + "         TabIndex        =   44";
        S = S + N + "         ToolTipText     =   \"Select the number of months to be Same As Cash.\"";
        S = S + N + "         Top             =   5880";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CheckBox chkAutoARNO ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Auto A/R No:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   420";
        S = S + N + "         TabIndex        =   9";
        S = S + N + "         Top             =   2520";
        S = S + N + "         Width           =   1275";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtBalDueLateCharge ";
        S = S + N + "         BeginProperty Font ";
        S = S + N + "            Name            =   \"MS Sans Serif\"";
        S = S + N + "            Size            =   9.75";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   400";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         Height          =   375";
        S = S + N + "         Left            =   3360";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   22";
        S = S + N + "         Top             =   3360";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtAddlPaymentsMade ";
        S = S + N + "         BeginProperty Font ";
        S = S + N + "            Name            =   \"MS Sans Serif\"";
        S = S + N + "            Size            =   9.75";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   400";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         Height          =   375";
        S = S + N + "         Left            =   3300";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   20";
        S = S + N + "         ToolTipText     =   \"Additional Payments Made.\"";
        S = S + N + "         Top             =   2760";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtPaymentWillBe ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         BeginProperty Font ";
        S = S + N + "            Name            =   \"Arial\"";
        S = S + N + "            Size            =   12";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   700";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         Height          =   405";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   54";
        S = S + N + "         Top             =   7320";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtRate ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   2880";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   41";
        S = S + N + "         ToolTipText     =   \"Interest Rate.\"";
        S = S + N + "         Top             =   5520";
        S = S + N + "         Width           =   615";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Frame fraLateChargesApplied ";
        S = S + N + "         Height          =   1275";
        S = S + N + "         Left            =   720";
        S = S + N + "         TabIndex        =   4";
        S = S + N + "         Top             =   1080";
        S = S + N + "         Width           =   3135";
        S = S + N + "         Begin VB.OptionButton optLate26 ";
        S = S + N + "            Caption         =   \"Due On The 20th.  Late on 26th\"";
        S = S + N + "            Height          =   255";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   8";
        S = S + N + "            Top             =   900";
        S = S + N + "            Width           =   2655";
        S = S + N + "         End";
        S = S + N + "         Begin VB.OptionButton optLate16 ";
        S = S + N + "            Caption         =   \"Due On The 10th.  Late on 16th\"";
        S = S + N + "            Height          =   255";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   7";
        S = S + N + "            Top             =   660";
        S = S + N + "            Width           =   2655";
        S = S + N + "         End";
        S = S + N + "         Begin VB.OptionButton optLate6 ";
        S = S + N + "            Caption         =   \"Due On The 1st.  Late on 6th\"";
        S = S + N + "            Height          =   255";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   6";
        S = S + N + "            Top             =   420";
        S = S + N + "            Width           =   2655";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Label lblLateChargesApplied ";
        S = S + N + "            Caption         =   \"Late Charges Will Be Applied:\"";
        S = S + N + "            BeginProperty Font ";
        S = S + N + "               Name            =   \"MS Sans Serif\"";
        S = S + N + "               Size            =   8.25";
        S = S + N + "               Charset         =   0";
        S = S + N + "               Weight          =   700";
        S = S + N + "               Underline       =   0   'False";
        S = S + N + "               Italic          =   0   'False";
        S = S + N + "               Strikethrough   =   0   'False";
        S = S + N + "            EndProperty";
        S = S + N + "            Height          =   255";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   5";
        S = S + N + "            Top             =   180";
        S = S + N + "            Width           =   2655";
        S = S + N + "         End";
        S = S + N + "      End";
        S = S + N + "      Begin MSComCtl2.DTPicker dteDate1 ";
        S = S + N + "         Height          =   375";
        S = S + N + "         Left            =   360";
        S = S + N + "         TabIndex        =   0";
        S = S + N + "         Top             =   240";
        S = S + N + "         Width           =   1575";
        S = S + N + "         _ExtentX        =   2778";
        S = S + N + "         _ExtentY        =   661";
        S = S + N + "         _Version        =   393216";
        S = S + N + "         BeginProperty Font {0BE35203-8F91-11CE-9DE3-00AA004BB851} ";
        S = S + N + "            Name            =   \"MS Sans Serif\"";
        S = S + N + "            Size            =   9.75";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   400";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         CalendarTitleBackColor=   8454143";
        S = S + N + "         CustomFormat    =   \"MM/dd/yyyy\"";
        S = S + N + "         Format          =   121569283";
        S = S + N + "         CurrentDate     =   36893";
        S = S + N + "      End";
        S = S + N + "      Begin MSComCtl2.DTPicker dteDate2 ";
        S = S + N + "         Height          =   375";
        S = S + N + "         Left            =   360";
        S = S + N + "         TabIndex        =   2";
        S = S + N + "         Top             =   600";
        S = S + N + "         Width           =   1575";
        S = S + N + "         _ExtentX        =   2778";
        S = S + N + "         _ExtentY        =   661";
        S = S + N + "         _Version        =   393216";
        S = S + N + "         BeginProperty Font {0BE35203-8F91-11CE-9DE3-00AA004BB851} ";
        S = S + N + "            Name            =   \"MS Sans Serif\"";
        S = S + N + "            Size            =   9.75";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   400";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         CalendarTitleBackColor=   8454143";
        S = S + N + "         CustomFormat    =   \"MM/dd/yyyy\"";
        S = S + N + "         Format          =   121569283";
        S = S + N + "         CurrentDate     =   36894";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtFinanceChargeSalesTax ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         Locked          =   -1  'True";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   50";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   6720";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtFinanceCharges ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   48";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   6480";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtDeferredInt ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         Locked          =   -1  'True";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   46";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   6240";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.ComboBox cboDeferred ";
        S = S + N + "         Height          =   315";
        S = S + N + "         ItemData        =   \"ArPaySetUp.frx\":030E";
        S = S + N + "         Left            =   2880";
        S = S + N + "         List            =   \"ArPaySetUp.frx\":0310";
        S = S + N + "         Style           =   2  'Dropdown List";
        S = S + N + "         TabIndex        =   65";
        S = S + N + "         ToolTipText     =   \"Select the number of months to be Same As Cash.\"";
        S = S + N + "         Top             =   5880";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtFinanceAmount ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   40";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   5640";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtMonthsToFinance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   5";
        S = S + N + "         TabIndex        =   38";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   5400";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CheckBox chkProperty ";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   2820";
        S = S + N + "         TabIndex        =   33";
        S = S + N + "         Top             =   4680";
        S = S + N + "         Width           =   255";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtPropertyInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   32";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   4680";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CheckBox chkAccident ";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   2820";
        S = S + N + "         TabIndex        =   30";
        S = S + N + "         Top             =   4440";
        S = S + N + "         Width           =   255";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtAccidentInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   29";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   4440";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.CheckBox chkLife ";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   2820";
        S = S + N + "         TabIndex        =   27";
        S = S + N + "         Top             =   4200";
        S = S + N + "         Width           =   255";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtLifeInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   26";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   4200";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtDocFee ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   24";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   3960";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtSubTotal ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         Locked          =   -1  'True";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   18";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   3480";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtOrigDeposit ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   16";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   3240";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtGrossSale ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   14";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   3000";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtPrevBalance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   10";
        S = S + N + "         TabIndex        =   12";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   2760";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.TextBox txtArNo ";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   1800";
        S = S + N + "         MaxLength       =   50";
        S = S + N + "         TabIndex        =   10";
        S = S + N + "         Text            =   \" \"";
        S = S + N + "         Top             =   2520";
        S = S + N + "         Width           =   975";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Frame fraMath ";
        S = S + N + "         Height          =   1695";
        S = S + N + "         Left            =   3000";
        S = S + N + "         TabIndex        =   71";
        S = S + N + "         Top             =   6840";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   1455";
        S = S + N + "         Begin VB.Label lblMathTotal ";
        S = S + N + "            Alignment       =   1  'Right Justify";
        S = S + N + "            Caption         =   \"$5999.38\"";
        S = S + N + "            Height          =   230";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   78";
        S = S + N + "            Top             =   1440";
        S = S + N + "            Width           =   975";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Label lblMathLastPay ";
        S = S + N + "            Alignment       =   1  'Right Justify";
        S = S + N + "            Caption         =   \"$499.38\"";
        S = S + N + "            Height          =   240";
        S = S + N + "            Left            =   360";
        S = S + N + "            TabIndex        =   77";
        S = S + N + "            Top             =   1080";
        S = S + N + "            Width           =   855";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Line linSum2 ";
        S = S + N + "            X1              =   120";
        S = S + N + "            X2              =   1320";
        S = S + N + "            Y1              =   1320";
        S = S + N + "            Y2              =   1320";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Label lblMathAdd ";
        S = S + N + "            AutoSize        =   -1  'True";
        S = S + N + "            Caption         =   \"+\"";
        S = S + N + "            Height          =   195";
        S = S + N + "            Left            =   225";
        S = S + N + "            TabIndex        =   76";
        S = S + N + "            Top             =   1080";
        S = S + N + "            Width           =   90";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Label lblMathMonthlyTotal ";
        S = S + N + "            Alignment       =   1  'Right Justify";
        S = S + N + "            Caption         =   \"$5500.00\"";
        S = S + N + "            Height          =   255";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   75";
        S = S + N + "            Top             =   840";
        S = S + N + "            Width           =   975";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Label lblMathMontlyMonths ";
        S = S + N + "            Alignment       =   1  'Right Justify";
        S = S + N + "            Caption         =   \"11\"";
        S = S + N + "            Height          =   240";
        S = S + N + "            Left            =   480";
        S = S + N + "            TabIndex        =   74";
        S = S + N + "            Top             =   480";
        S = S + N + "            Width           =   735";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Line linSum ";
        S = S + N + "            X1              =   120";
        S = S + N + "            X2              =   1320";
        S = S + N + "            Y1              =   720";
        S = S + N + "            Y2              =   720";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Label lblMathMultiply ";
        S = S + N + "            AutoSize        =   -1  'True";
        S = S + N + "            Caption         =   \"x\"";
        S = S + N + "            Height          =   195";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   73";
        S = S + N + "            Top             =   480";
        S = S + N + "            Width           =   75";
        S = S + N + "         End";
        S = S + N + "         Begin VB.Label lblMathMonthly ";
        S = S + N + "            Alignment       =   1  'Right Justify";
        S = S + N + "            Caption         =   \"$500.00\"";
        S = S + N + "            Height          =   255";
        S = S + N + "            Left            =   240";
        S = S + N + "            TabIndex        =   72";
        S = S + N + "            Top             =   240";
        S = S + N + "            Width           =   975";
        S = S + N + "         End";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Frame fraCoupons ";
        S = S + N + "         Height          =   732";
        S = S + N + "         Left            =   2880";
        S = S + N + "         TabIndex        =   61";
        S = S + N + "         Top             =   6120";
        S = S + N + "         Width           =   1632";
        S = S + N + "         Begin VB.OptionButton optWeekly ";
        S = S + N + "            Caption         =   \"&Weekly Coupons\"";
        S = S + N + "            Height          =   192";
        S = S + N + "            Left            =   60";
        S = S + N + "            TabIndex        =   60";
        S = S + N + "            Top             =   420";
        S = S + N + "            Width           =   1512";
        S = S + N + "         End";
        S = S + N + "         Begin VB.OptionButton optMonthly ";
        S = S + N + "            Caption         =   \"&Monthly Coupons\"";
        S = S + N + "            Height          =   192";
        S = S + N + "            Left            =   60";
        S = S + N + "            TabIndex        =   59";
        S = S + N + "            Top             =   180";
        S = S + N + "            Value           =   -1  'True";
        S = S + N + "            Width           =   1550";
        S = S + N + "         End";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblTotalCaption ";
        S = S + N + "         AutoSize        =   -1  'True";
        S = S + N + "         Caption         =   \"Total:\"";
        S = S + N + "         Height          =   195";
        S = S + N + "         Left            =   2880";
        S = S + N + "         TabIndex        =   81";
        S = S + N + "         Top             =   3840";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   405";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblTotal ";
        S = S + N + "         Appearance      =   0  'Flat";
        S = S + N + "         BackColor       =   &H80000005&";
        S = S + N + "         BorderStyle     =   1  'Fixed Single";
        S = S + N + "         ForeColor       =   &H80000008&";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   3360";
        S = S + N + "         TabIndex        =   80";
        S = S + N + "         Top             =   3840";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   855";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblUnemploymentInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Unempl. Insurance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   120";
        S = S + N + "         TabIndex        =   34";
        S = S + N + "         Top             =   4920";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   1575";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblTotalBalance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Total Balance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   51";
        S = S + N + "         Top             =   6960";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblFinanceChargeSalesTax ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Sales Tax:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   49";
        S = S + N + "         Top             =   6720";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblAPR ";
        S = S + N + "         Appearance      =   0  'Flat";
        S = S + N + "         BorderStyle     =   1  'Fixed Single";
        S = S + N + "         ForeColor       =   &H80000008&";
        S = S + N + "         Height          =   285";
        S = S + N + "         Left            =   3600";
        S = S + N + "         TabIndex        =   42";
        S = S + N + "         ToolTipText     =   \"APR\"";
        S = S + N + "         Top             =   5520";
        S = S + N + "         Width           =   495";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblSubTotal ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Sub Total:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   480";
        S = S + N + "         TabIndex        =   17";
        S = S + N + "         Top             =   3480";
        S = S + N + "         Width           =   1215";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblCashOpt ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Cash Option:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   480";
        S = S + N + "         TabIndex        =   43";
        S = S + N + "         Top             =   5880";
        S = S + N + "         Width           =   1200";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblDeferredInt ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Deferment Interest:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   45";
        S = S + N + "         Top             =   6240";
        S = S + N + "         Visible         =   0   'False";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblDeferred ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Pay Def\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   3000";
        S = S + N + "         TabIndex        =   58";
        S = S + N + "         Top             =   5920";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblFirstPaymentDue ";
        S = S + N + "         Caption         =   \"First Payment Due\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   2040";
        S = S + N + "         TabIndex        =   3";
        S = S + N + "         Top             =   720";
        S = S + N + "         Width           =   1335";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblDelDate ";
        S = S + N + "         Caption         =   \"Delivery Date\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   2040";
        S = S + N + "         TabIndex        =   1";
        S = S + N + "         Top             =   360";
        S = S + N + "         Width           =   1335";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblAcctNo ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Account No:\"";
        S = S + N + "         BeginProperty Font ";
        S = S + N + "            Name            =   \"MS Sans Serif\"";
        S = S + N + "            Size            =   8.25";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   700";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         Height          =   195";
        S = S + N + "         Left            =   480";
        S = S + N + "         TabIndex        =   66";
        S = S + N + "         Top             =   8160";
        S = S + N + "         Width           =   1155";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblAccountNo ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         BeginProperty Font ";
        S = S + N + "            Name            =   \"MS Sans Serif\"";
        S = S + N + "            Size            =   9.75";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   700";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   1800";
        S = S + N + "         TabIndex        =   67";
        S = S + N + "         Top             =   8160";
        S = S + N + "         Width           =   915";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblBalDueLateCharge ";
        S = S + N + "         Caption         =   \"Bal Due Late Chg:\"";
        S = S + N + "         Height          =   195";
        S = S + N + "         Left            =   2880";
        S = S + N + "         TabIndex        =   21";
        S = S + N + "         Top             =   3120";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblAddlPayments ";
        S = S + N + "         Caption         =   \"Additional Pmts Made:\"";
        S = S + N + "         Height          =   195";
        S = S + N + "         Left            =   2880";
        S = S + N + "         TabIndex        =   19";
        S = S + N + "         ToolTipText     =   \"Additional Payments Made.\"";
        S = S + N + "         Top             =   2520";
        S = S + N + "         Width           =   1635";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblContract ";
        S = S + N + "         Alignment       =   2  'Center";
        S = S + N + "         Caption         =   \"Contract \"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   3120";
        S = S + N + "         TabIndex        =   69";
        S = S + N + "         Top             =   7560";
        S = S + N + "         Width           =   1215";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblPrevBal ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Previous Balance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   11";
        S = S + N + "         Top             =   2760";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblPaymentWillBe ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Payment Will Be:\"";
        S = S + N + "         BeginProperty Font ";
        S = S + N + "            Name            =   \"MS Sans Serif\"";
        S = S + N + "            Size            =   8.25";
        S = S + N + "            Charset         =   0";
        S = S + N + "            Weight          =   700";
        S = S + N + "            Underline       =   0   'False";
        S = S + N + "            Italic          =   0   'False";
        S = S + N + "            Strikethrough   =   0   'False";
        S = S + N + "         EndProperty";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   53";
        S = S + N + "         Top             =   7320";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblPropertyInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Property Insurance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   31";
        S = S + N + "         Top             =   4680";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblAccidentInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Accident Insurance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   28";
        S = S + N + "         Top             =   4440";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblLifeInsurance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Life Insurance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   25";
        S = S + N + "         Top             =   4200";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblDocFee ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Documentation Fee:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   23";
        S = S + N + "         Top             =   3960";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblFinanceCharges ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Finance Charges:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   47";
        S = S + N + "         Top             =   6480";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblMonthsToFinance ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Months To Finance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   37";
        S = S + N + "         Top             =   5400";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblFinanceAmount ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Amount To Finance:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   39";
        S = S + N + "         Top             =   5640";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblOrigDeposit ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Original Deposit:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   15";
        S = S + N + "         Top             =   3240";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "      Begin VB.Label lblGrossSale ";
        S = S + N + "         Alignment       =   1  'Right Justify";
        S = S + N + "         Caption         =   \"Gross Sale W/Tax:\"";
        S = S + N + "         Height          =   255";
        S = S + N + "         Left            =   240";
        S = S + N + "         TabIndex        =   13";
        S = S + N + "         Top             =   3000";
        S = S + N + "         Width           =   1455";
        S = S + N + "      End";
        S = S + N + "   End";
        S = S + N + "End";
        S = S + N + "Attribute VB_Name = \"ARPaySetUp\"";
        S = S + N + "Attribute VB_GlobalNameSpace = False";
        S = S + N + "Attribute VB_Creatable = False";
        S = S + N + "Attribute VB_PredeclaredId = True";
        S = S + N + "Attribute VB_Exposed = False";
        S = S + N + "";

        TestCaseFrm2 = S;
        return TestCaseFrm2;
    }

    public static string TestCaseFunc()
    {
        string TestCaseFunc = "";
        string R = "";
        string N = "";
        string M = "";

        R = "";
        N = vbCrLf;
        M = "";

        R = R + M + "Private Function AlreadyMadeSameAsCash() As Boolean";
        //  R = R & N & "  Dim R As Recordset"
        //  R = R & N & "  Set R = GetRecordsetBySQL(""SELECT * FROM [Transactions] WHERE [ArNo]="""""" & ProtectSQL(ArNo) & """""" ORDER BY [TransDate] ASC, [TransactionID] ASC"", , GetDatabaseAtLocation())"
        R = R + N + "  Do While Not R.EOF";
        //  R = R & N & "    If LCase(Left(R(""Type""), 7)) = LCase(arPT_New) Then AlreadyMadeSameAsCash = False"
        //  R = R & N & "    If LCase(Left(R(""Receipt""), 12)) = ""same as cash"" Then AlreadyMadeSameAsCash = True"
        R = R + N + "    R.MoveNext";
        R = R + N + "  Loop";
        R = R + N + "  DisposeDA R";
        R = R + N + "End Function";

        TestCaseFunc = R;
        return TestCaseFunc;
    }
}
