public static class VBConstants
{
    public const int vbKeyLButton = 1; // Left mouse button
    public const int vbKeyRButton = 2;  // CANCEL mouse button 
    public const int vbKeyCancel = 3;  // Middle key  
    public const int vbKeyMButton = 4;  // BACKSPACE mouse button 
    public const int vbKeyBack = 8;  // TAB key  
    public const int vbKeyTab = 9;  //  key  
    public const int vbKeyClear = 12;  //  CLEAR key 
    public const int vbKeyReturn = 13;  //  ENTER key 
    public const int vbKeyShift = 16;  //  SHIFT key 
    public const int vbKeyControl = 17;  //  CTRL key 
    public const int vbKeyMenu = 18;  //  MENU key 
    public const int vbKeyPause = 19;  //  PAUSE key 
    public const int vbKeyCapital = 20;  //  CAPS lock key
    public const int vbKeyEscape = 27;  //  ESC key 
    public const int vbKeySpace = 32;  //  SPACEBAR key 
    public const int vbKeyPageUp = 33;  //  PAGE UP key
    public const int vbKeyPageDown = 34;  //  PAGE DOWN key
    public const int vbKeyEnd = 35;  //  END key 
    public const int vbKeyHome = 36;  //  HOME key 
    public const int vbKeyLeft = 37;  //  LEFT ARROW key
    public const int vbKeyUp = 38;  //  UP ARROW key
    public const int vbKeyRight = 39;  //  RIGHT ARROW key
    public const int vbKeyDown = 40;  //  DOWN ARROW key
    public const int vbKeySelect = 41;  //  SELECT key 
    public const int vbKeyPrint = 42;  //  print SCREEN key
    public const int vbKeyExecute = 43;  //  EXECUTE key 
    public const int vbKeySnapshot = 44;  //  SNAPSHOT key 
    public const int vbKeyInsert = 45;  //  INS key 
    public const int vbKeyDelete = 46;  //  DEL key 
    public const int vbKeyHelp = 47;  // NUM HELP key 
    public const int vbKeyNumlock = 144;  //  lock key 
    public const int vbKeyA = 65;  //  A key 
    public const int vbKeyB = 66;  //  B key 
    public const int vbKeyC = 67;  //  C key 
    public const int vbKeyD = 68;  //  D key 
    public const int vbKeyE = 69;  //  E key 
    public const int vbKeyF = 70;  //  F key 
    public const int vbKeyG = 71;  //  G key 
    public const int vbKeyH = 72;  //  H key 
    public const int vbKeyI = 73;  //  I key 
    public const int vbKeyJ = 74;  //  J key 
    public const int vbKeyK = 75;  //  K key 
    public const int vbKeyL = 76;  //  L key 
    public const int vbKeyM = 77;  //  M key 
    public const int vbKeyN = 78;  //  N key 
    public const int vbKeyO = 79;  //  O key 
    public const int vbKeyP = 80;  //  P key 
    public const int vbKeyQ = 81;  //  Q key 
    public const int vbKeyR = 82;  //  R key 
    public const int vbKeyS = 83;  //  S key 
    public const int vbKeyT = 84;  //  T key 
    public const int vbKeyU = 85;  //  U key 
    public const int vbKeyV = 86;  //  V key 
    public const int vbKeyW = 87;  //  W key 
    public const int vbKeyX = 88;  //  X key 
    public const int vbKeyY = 89;  //  Y key 
    public const int vbKeyZ = 90;  //  Z key 
    public const int vbKey0 = 48;  //  0 key 
    public const int vbKey1 = 49;  //  1 key 
    public const int vbKey2 = 50;  //  2 key 
    public const int vbKey3 = 51;  //  3 key 
    public const int vbKey4 = 52;  //  4 key 
    public const int vbKey5 = 53;  //  5 key 
    public const int vbKey6 = 54;  //  6 key 
    public const int vbKey7 = 55;  //  7 key 
    public const int vbKey8 = 56;  //  8 key 
    public const int vbKey9 = 57;  //  9 key 
    public const int vbKeyNumpad0 = 96;  //  0 key 
    public const int vbKeyNumpad1 = 97;  //  1 key 
    public const int vbKeyNumpad2 = 98;  //  2 key 
    public const int vbKeyNumpad3 = 99;  // 4 3 key 
    public const int vbKeyNumpad4 = 100;  // 5 key  
    public const int vbKeyNumpad5 = 101;  // 6 key  
    public const int vbKeyNumpad6 = 102;  // 7 key  
    public const int vbKeyNumpad7 = 103;  // 8 key  
    public const int vbKeyNumpad8 = 104;  // 9 key  
    public const int vbKeyNumpad9 = 105;  // MULTIPLICATION key  
    public const int vbKeyMultiply = 106;  // PLUS SIGN (*) key
    public const int vbKeyAdd = 107;  // ENTER SIGN (+) key
    public const int vbKeySeparator = 108;  // MINUS (keypad) key 
    public const int vbKeySubtract = 109;  // DECIMAL SIGN (-) key
    public const int vbKeyDecimal = 110;  // DIVISION POINT(.) key 
    public const int vbKeyDivide = 111;  // F1 SIGN (/) key
    public const int vbKeyF1 = 112;  // F2 key  
    public const int vbKeyF2 = 113;  // F3 key  
    public const int vbKeyF3 = 114;  // F4 key  
    public const int vbKeyF4 = 115;  // F5 key  
    public const int vbKeyF5 = 116;  // F6 key  
    public const int vbKeyF6 = 117;  // F7 key  
    public const int vbKeyF7 = 118;  // F8 key  
    public const int vbKeyF8 = 119;  // F9 key  
    public const int vbKeyF9 = 120;  // F10 key  
    public const int vbKeyF10 = 121;  // F11 key  
    public const int vbKeyF11 = 122;  // F12 key  
    public const int vbKeyF12 = 123;  // F13 key  
    public const int vbKeyF13 = 124;  // F14 key  
    public const int vbKeyF14 = 125;  // F15 key  
    public const int vbKeyF15 = 126;  // F16 key  
    public const int vbKeyF16 = 127;  //  key  
    public const int vbBlack = 0x0;  // BLACK
    public const int vbBlue = 0x0000FF;  // BLUE
    public const int vbCyan = 0x00FFFF;  // CYAN
    public const int vbGreen = 0x00FF00;  // GREEN
    public const int vbMagenta = 0xFFFF00;  // MAGENTA
    public const int vbRed = 0xFF0000;  // RED
    public const int vbWhite = 0xFFFFFF;  // WHITE
    public const int vbYellow = 0xFF00FF;  // YELLOW
    public const int vbModal = 0x1;
    public enum AlignConstants { vbAlignNone = 0, vbAlignTop = 1, vbAlignBottom = 2, vbAlignLeft = 3, vbAlignRight = 4, vbLeftJustify = 5, vbRightJustify = 6, vbCenter = 7 }
    public enum AlignmentConstants : byte { vbLeftJustify = 0, vbRightJustify = 1, vbCenter = 2 }

    // Cursors
    public const int vbDefault = 0;
    public const int vbArrow = 1;
    public const int vbHourglass = 11;

    public const int flexAlignLeftCenter = 0;
    public const int flexAlignRightCenter = 0;
    public const int flexAlignCenterCenter = 0;
}
